name: openpaygo-token

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-openpaygo-token:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install `openpaygo-token`
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run Python Tests
        run: |
          python tests/full_test_procedure.py
          python tests/simple_scenario_test.py
          python tests/test_spreadsheet_generator.py
